from src.types.api import (
    PlanetConfigResponse,
    PlanetImageryCategory,
    PlanetImageryMode,
    PlanetTerrainConfig,
)

GIBS_WMTS_URL = "https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/wmts.cgi"
NASA_EARTHDATA_URL = "https://www.earthdata.nasa.gov/data/projects/gibs"
BLUE_MARBLE_URL = "https://visibleearth.nasa.gov/collection/1484/blue-marble"
BLACK_MARBLE_URL = "https://blackmarble.gsfc.nasa.gov/"
OPERA_RTC_S1_URL = "https://gibs.earthdata.nasa.gov/layer-metadata/v1.0/OPERA_L2_Radiometric_Terrain_Corrected_SAR_Sentinel-1.json"


def build_planet_config() -> PlanetConfigResponse:
    categories = [
        PlanetImageryCategory(
            id="base-day",
            title="Base / Day",
            description="Default-friendly daytime imagery with the strongest global visual coherence.",
            order=10,
        ),
        PlanetImageryCategory(
            id="night",
            title="Night",
            description="Global night-light visualization for dark-side context.",
            order=20,
        ),
        PlanetImageryCategory(
            id="seasonal",
            title="Seasonal",
            description="Cloud-free Blue Marble seasonal composites for globe-scale seasonal context.",
            order=30,
        ),
        PlanetImageryCategory(
            id="infrared-false-color",
            title="Infrared / False Color",
            description="False-color imagery tuned for vegetation, burn, snow, and surface differentiation.",
            order=40,
        ),
        PlanetImageryCategory(
            id="analysis-friendly",
            title="Analysis / Thematic",
            description="Specialized thematic layers for analysis workflows, not default basemap viewing.",
            order=50,
        ),
        PlanetImageryCategory(
            id="radar-sar",
            title="Analysis / Radar-SAR",
            description="Radar backscatter and radar-derived analytical products for cloud-insensitive interpretation.",
            order=60,
        ),
    ]
    imagery_modes = [
        PlanetImageryMode(
            id="day-cloudless-default",
            title="Cloudless Blue Marble",
            category="base-day",
            source="NASA Blue Marble",
            source_url=BLUE_MARBLE_URL,
            short_description="Cloud-free global composite for the default Earth view.",
            short_caveat="Static composite, not current conditions.",
            display_tags=["Default-ready", "Cloud-free", "Composite"],
            mode_role="default-basemap",
            sensor_family="optical",
            historical_fidelity="composite-reference",
            replay_short_note="Replay tracks are historical events over a non-historical composite basemap.",
            temporal_nature="static-composite",
            cloud_behavior="cloud-free",
            resolution_notes="Global cloud-free composite imagery suitable for full-globe viewing rather than local high-resolution inspection.",
            license_access_notes="NASA Earthdata / Visible Earth public imagery access. Preserve NASA attribution in product labeling.",
            default_ready=True,
            analysis_ready=False,
            description="Default beautiful-Earth mode using a cloud-free Blue Marble composite instead of weather-affected live imagery.",
            interpretation_caveats="This is not live imagery. It is a cloud-free composite intended for coherent global context.",
            provider_type="wmts",
            provider_url=GIBS_WMTS_URL,
            provider_layer="BlueMarble_ShadedRelief_Bathymetry",
            provider_style="default",
            provider_format="image/jpeg",
            provider_tile_matrix_set_id="GoogleMapsCompatible_Level8",
            provider_maximum_level=8,
        ),
        PlanetImageryMode(
            id="day-daily-true-color",
            title="Daily True Color",
            category="base-day",
            source="NASA GIBS / MODIS Terra",
            source_url=NASA_EARTHDATA_URL,
            short_description="Recent daily true-color imagery for current context.",
            short_caveat="Weather-affected and often cloudy.",
            display_tags=["Daily", "Weather-affected", "Analysis-friendly"],
            mode_role="optional-basemap",
            sensor_family="optical",
            historical_fidelity="daily-approximate",
            replay_short_note="Replay tracks may not align exactly with the displayed daily image date.",
            temporal_nature="daily",
            cloud_behavior="weather-affected",
            resolution_notes="Global daily true-color imagery. Good for recent context, but cloud cover and daily latency are expected.",
            license_access_notes="NASA GIBS public WMTS access. Preserve NASA EOSDIS / GIBS attribution.",
            default_ready=False,
            analysis_ready=True,
            description="Recent daily true-color view pulled from NASA GIBS instead of a cloudless aesthetic composite.",
            interpretation_caveats="This mode can be cloudy, smoky, or otherwise weather-affected. It is recent daily imagery, not a cloud-free mosaic.",
            provider_type="wmts",
            provider_url=GIBS_WMTS_URL,
            provider_layer="MODIS_Terra_CorrectedReflectance_TrueColor",
            provider_style="default",
            provider_format="image/jpeg",
            provider_tile_matrix_set_id="GoogleMapsCompatible_Level9",
            provider_maximum_level=9,
            provider_time_strategy="daily-yesterday-utc",
        ),
        PlanetImageryMode(
            id="night-lights",
            title="Black Marble Night Lights",
            category="night",
            source="NASA Black Marble / VIIRS",
            source_url=BLACK_MARBLE_URL,
            short_description="Global night-light composite for human settlement context.",
            short_caveat="Composite night lights, not live activity.",
            display_tags=["Night", "Cloud-free", "Composite"],
            mode_role="optional-basemap",
            sensor_family="thematic",
            historical_fidelity="composite-reference",
            replay_short_note="Replay tracks are historical events over a non-time-specific night-light composite.",
            temporal_nature="static-composite",
            cloud_behavior="cloud-free",
            resolution_notes="Global night-light composite tuned for macro-scale human activity patterns, not fine local lighting inspection.",
            license_access_notes="NASA Black Marble public imagery access. Preserve NASA attribution in UI and docs.",
            default_ready=True,
            analysis_ready=True,
            description="Night-side global view based on Black Marble city-light composites.",
            interpretation_caveats="This is a composite night-light product and should not be interpreted as current, live electricity or occupancy conditions.",
            provider_type="wmts",
            provider_url=GIBS_WMTS_URL,
            provider_layer="VIIRS_Black_Marble",
            provider_style="default",
            provider_format="image/jpeg",
            provider_tile_matrix_set_id="GoogleMapsCompatible_Level8",
            provider_maximum_level=8,
        ),
        PlanetImageryMode(
            id="season-winter",
            title="Winter Composite",
            category="seasonal",
            source="NASA Blue Marble Next Generation",
            source_url=BLUE_MARBLE_URL,
            short_description="January seasonal composite proxy for winter context.",
            short_caveat="Seasonal proxy, not this year's winter.",
            display_tags=["Seasonal", "Cloud-free", "Composite"],
            mode_role="optional-basemap",
            sensor_family="optical",
            historical_fidelity="composite-reference",
            replay_short_note="Replay tracks are historical events over a seasonal proxy composite.",
            temporal_nature="seasonal-composite",
            cloud_behavior="cloud-free",
            resolution_notes="Monthly Blue Marble composite used as a winter proxy at global scale.",
            license_access_notes="NASA Blue Marble public imagery access. Preserve NASA attribution.",
            default_ready=False,
            analysis_ready=False,
            description="Northern-hemisphere winter context using a January Blue Marble monthly composite.",
            interpretation_caveats="This is a seasonal composite proxy, not live winter conditions for the current year.",
            provider_type="wmts",
            provider_url=GIBS_WMTS_URL,
            provider_layer="BlueMarble_NextGeneration",
            provider_style="default",
            provider_format="image/jpeg",
            provider_tile_matrix_set_id="GoogleMapsCompatible_Level8",
            provider_maximum_level=8,
            provider_time_strategy="fixed",
            provider_time_value="2004-01-01",
        ),
        PlanetImageryMode(
            id="season-spring",
            title="Spring Composite",
            category="seasonal",
            source="NASA Blue Marble Next Generation",
            source_url=BLUE_MARBLE_URL,
            short_description="April seasonal composite proxy for spring context.",
            short_caveat="Seasonal proxy, not this year's spring.",
            display_tags=["Seasonal", "Cloud-free", "Composite"],
            mode_role="optional-basemap",
            sensor_family="optical",
            historical_fidelity="composite-reference",
            replay_short_note="Replay tracks are historical events over a seasonal proxy composite.",
            temporal_nature="seasonal-composite",
            cloud_behavior="cloud-free",
            resolution_notes="Monthly Blue Marble composite used as a spring proxy at global scale.",
            license_access_notes="NASA Blue Marble public imagery access. Preserve NASA attribution.",
            default_ready=False,
            analysis_ready=False,
            description="Northern-hemisphere spring context using an April Blue Marble monthly composite.",
            interpretation_caveats="This is a seasonal composite proxy, not current-year spring conditions.",
            provider_type="wmts",
            provider_url=GIBS_WMTS_URL,
            provider_layer="BlueMarble_NextGeneration",
            provider_style="default",
            provider_format="image/jpeg",
            provider_tile_matrix_set_id="GoogleMapsCompatible_Level8",
            provider_maximum_level=8,
            provider_time_strategy="fixed",
            provider_time_value="2004-04-01",
        ),
        PlanetImageryMode(
            id="season-summer",
            title="Summer Composite",
            category="seasonal",
            source="NASA Blue Marble Next Generation",
            source_url=BLUE_MARBLE_URL,
            short_description="July seasonal composite proxy for summer context.",
            short_caveat="Seasonal proxy, not this year's summer.",
            display_tags=["Seasonal", "Cloud-free", "Composite"],
            mode_role="optional-basemap",
            sensor_family="optical",
            historical_fidelity="composite-reference",
            replay_short_note="Replay tracks are historical events over a seasonal proxy composite.",
            temporal_nature="seasonal-composite",
            cloud_behavior="cloud-free",
            resolution_notes="Monthly Blue Marble composite used as a summer proxy at global scale.",
            license_access_notes="NASA Blue Marble public imagery access. Preserve NASA attribution.",
            default_ready=False,
            analysis_ready=False,
            description="Northern-hemisphere summer context using a July Blue Marble monthly composite.",
            interpretation_caveats="This is a seasonal composite proxy, not current-year summer imagery.",
            provider_type="wmts",
            provider_url=GIBS_WMTS_URL,
            provider_layer="BlueMarble_NextGeneration",
            provider_style="default",
            provider_format="image/jpeg",
            provider_tile_matrix_set_id="GoogleMapsCompatible_Level8",
            provider_maximum_level=8,
            provider_time_strategy="fixed",
            provider_time_value="2004-07-01",
        ),
        PlanetImageryMode(
            id="season-fall",
            title="Fall Composite",
            category="seasonal",
            source="NASA Blue Marble Next Generation",
            source_url=BLUE_MARBLE_URL,
            short_description="October seasonal composite proxy for autumn context.",
            short_caveat="Seasonal proxy, not this year's fall.",
            display_tags=["Seasonal", "Cloud-free", "Composite"],
            mode_role="optional-basemap",
            sensor_family="optical",
            historical_fidelity="composite-reference",
            replay_short_note="Replay tracks are historical events over a seasonal proxy composite.",
            temporal_nature="seasonal-composite",
            cloud_behavior="cloud-free",
            resolution_notes="Monthly Blue Marble composite used as a fall proxy at global scale.",
            license_access_notes="NASA Blue Marble public imagery access. Preserve NASA attribution.",
            default_ready=False,
            analysis_ready=False,
            description="Northern-hemisphere fall context using an October Blue Marble monthly composite.",
            interpretation_caveats="This is a seasonal composite proxy, not current-year autumn color for any specific region.",
            provider_type="wmts",
            provider_url=GIBS_WMTS_URL,
            provider_layer="BlueMarble_NextGeneration",
            provider_style="default",
            provider_format="image/jpeg",
            provider_tile_matrix_set_id="GoogleMapsCompatible_Level8",
            provider_maximum_level=8,
            provider_time_strategy="fixed",
            provider_time_value="2004-10-01",
        ),
        PlanetImageryMode(
            id="false-color-vegetation",
            title="False Color Vegetation",
            category="infrared-false-color",
            source="NASA GIBS / MODIS Terra",
            source_url=NASA_EARTHDATA_URL,
            short_description="False-color land-surface mode emphasizing vegetation contrast.",
            short_caveat="Analytical rendering with cloud limits.",
            display_tags=["False color", "Daily", "Analysis-friendly"],
            mode_role="analysis-layer",
            sensor_family="optical",
            historical_fidelity="daily-approximate",
            replay_short_note="Replay tracks may not align with the exact observation date of this analytical daily layer.",
            temporal_nature="daily",
            cloud_behavior="weather-affected",
            resolution_notes="Daily false-color global imagery emphasizing vegetation and burn/surface contrast over natural-looking color.",
            license_access_notes="NASA GIBS public WMTS access. Preserve NASA EOSDIS / GIBS attribution.",
            default_ready=False,
            analysis_ready=True,
            description="False-color land-surface mode using MODIS corrected reflectance bands 7-2-1 for vegetation and burn contrast.",
            interpretation_caveats="This is a false-color analytical rendering. It is not natural color, and cloud cover still affects interpretation.",
            provider_type="wmts",
            provider_url=GIBS_WMTS_URL,
            provider_layer="MODIS_Terra_CorrectedReflectance_Bands721",
            provider_style="default",
            provider_format="image/jpeg",
            provider_tile_matrix_set_id="GoogleMapsCompatible_Level9",
            provider_maximum_level=9,
            provider_time_strategy="daily-yesterday-utc",
        ),
        PlanetImageryMode(
            id="snow-ice",
            title="Snow and Ice Distinction",
            category="analysis-friendly",
            source="NASA GIBS / MODIS Terra",
            source_url=NASA_EARTHDATA_URL,
            short_description="Daily thematic snow-cover view for cryosphere context.",
            short_caveat="Analytical layer, not photorealistic imagery.",
            display_tags=["Snow / ice", "Daily", "Analysis-friendly"],
            mode_role="analysis-layer",
            sensor_family="thematic",
            historical_fidelity="daily-approximate",
            replay_short_note="Replay tracks may not align with the exact date represented by this daily thematic layer.",
            temporal_nature="daily",
            cloud_behavior="weather-affected",
            resolution_notes="Daily analytical snow-cover product for broad global context rather than local operational snow depth decisions.",
            license_access_notes="NASA GIBS public WMTS access. Preserve NASA EOSDIS / GIBS attribution.",
            default_ready=False,
            analysis_ready=True,
            description="Analysis-oriented daily snow-cover view for distinguishing broad snow and cryosphere patterns.",
            interpretation_caveats="This mode is a thematic analytical layer, not a photorealistic Earth view. Cloud and sensing limits still matter.",
            provider_type="wmts",
            provider_url=GIBS_WMTS_URL,
            provider_layer="MODIS_Terra_NDSI_Snow_Cover",
            provider_style="default",
            provider_format="image/png",
            provider_tile_matrix_set_id="GoogleMapsCompatible_Level9",
            provider_maximum_level=9,
            provider_time_strategy="daily-yesterday-utc",
        ),
        PlanetImageryMode(
            id="radar-sar-opera-rtc",
            title="SAR Backscatter (OPERA RTC-S1)",
            category="radar-sar",
            source="NASA GIBS / OPERA RTC-S1 (Sentinel-1)",
            source_url=OPERA_RTC_S1_URL,
            short_description="False-color SAR backscatter for cloud-insensitive surface analysis.",
            short_caveat="Radar interpretation differs from optical imagery; expect speckle and geometry effects.",
            display_tags=["Radar", "SAR", "Multi-day", "Analysis-friendly"],
            mode_role="analysis-layer",
            sensor_family="radar",
            historical_fidelity="multi-day-approximate",
            replay_short_note="Replay tracks are historical events over a multi-day SAR backscatter context, not a same-time optical ground truth.",
            temporal_nature="multi-day",
            cloud_behavior="cloud-insensitive",
            resolution_notes="Global browse layer from OPERA RTC-S1. Useful for broad interpretation, not local photoreal detail.",
            license_access_notes="NASA GIBS public WMTS access. Preserve NASA/OPERA/Sentinel-1 attribution.",
            default_ready=False,
            analysis_ready=True,
            description="Radiometrically terrain-corrected Sentinel-1 SAR backscatter browse layer rendered in false color for analysis workflows.",
            interpretation_caveats="This is SAR backscatter, not natural color. Brightness reflects radar response to surface roughness, moisture, structure, and geometry.",
            provider_type="wmts",
            provider_url=GIBS_WMTS_URL,
            provider_layer="OPERA_L2_Radiometric_Terrain_Corrected_SAR_Sentinel-1",
            provider_style="default",
            provider_format="image/png",
            provider_tile_matrix_set_id="GoogleMapsCompatible_Level9",
            provider_maximum_level=9,
        ),
    ]
    return PlanetConfigResponse(
        default_imagery_mode_id="day-cloudless-default",
        categories=categories,
        imagery_modes=imagery_modes,
        terrain=PlanetTerrainConfig(
            default_provider="ellipsoid",
            optional_provider="google-photorealistic-3d",
            notes="Terrain and 3D tiles remain separate from imagery modes. The globe stays fully 3D even when imagery changes.",
        ),
    )
