"""baseline schema

Revision ID: f5e35ec3725d
Revises: 
Create Date: 2026-03-14 21:01:16.062643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e35ec3725d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('focus_type', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_message', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wave', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wave_focus_type'), ['focus_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wave_last_error_at'), ['last_error_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wave_last_run_at'), ['last_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wave_last_success_at'), ['last_success_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wave_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_wave_status'), ['status'], unique=False)

    op.create_table('connector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wave_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('polling_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_message', sa.String(length=2000), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wave_id'], ['wave.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connector_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_last_error_at'), ['last_error_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_last_run_at'), ['last_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_last_success_at'), ['last_success_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_type'), ['type'], unique=False)
        batch_op.create_index('ix_connector_wave_enabled', ['wave_id', 'enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_connector_wave_id'), ['wave_id'], unique=False)

    op.create_table('discoveredsource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wave_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('parent_domain', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('discovery_method', sa.String(length=120), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('free_access', sa.Boolean(), nullable=True),
    sa.Column('suggested_connector_type', sa.String(length=80), nullable=True),
    sa.Column('description_summary', sa.String(length=2000), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('last_content_type', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['wave_id'], ['wave.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discoveredsource', schema=None) as batch_op:
        batch_op.create_index('ix_discovered_source_parent_domain', ['parent_domain'], unique=False)
        batch_op.create_index('ix_discovered_source_wave_relevance', ['wave_id', 'relevance_score'], unique=False)
        batch_op.create_index('ix_discovered_source_wave_source_type', ['wave_id', 'source_type'], unique=False)
        batch_op.create_index('ix_discovered_source_wave_stability', ['wave_id', 'stability_score'], unique=False)
        batch_op.create_index('ix_discovered_source_wave_status', ['wave_id', 'status'], unique=False)
        batch_op.create_index('ix_discovered_source_wave_url_unique', ['wave_id', 'url'], unique=True)
        batch_op.create_index(batch_op.f('ix_discoveredsource_discovered_at'), ['discovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveredsource_failure_count'), ['failure_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveredsource_free_access'), ['free_access'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveredsource_last_checked_at'), ['last_checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveredsource_last_content_type'), ['last_content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveredsource_last_http_status'), ['last_http_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveredsource_last_success_at'), ['last_success_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveredsource_parent_domain'), ['parent_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveredsource_relevance_score'), ['relevance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveredsource_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveredsource_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_discoveredsource_wave_id'), ['wave_id'], unique=False)

    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wave_id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.String(length=10000), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('raw_payload_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ),
    sa.ForeignKeyConstraint(['wave_id'], ['wave.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_collected_at'), ['collected_at'], unique=False)
        batch_op.create_index('ix_record_connector_collected_at', ['connector_id', 'collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_external_id'), ['external_id'], unique=False)
        batch_op.create_index('ix_record_wave_collected_at', ['wave_id', 'collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_record_wave_id'), ['wave_id'], unique=False)
        batch_op.create_index('ix_record_wave_source_type_collected', ['wave_id', 'source_type', 'collected_at'], unique=False)
        batch_op.create_index('ux_record_connector_external_id', ['connector_id', 'external_id'], unique=True)

    op.create_table('runhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wave_id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=7), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ),
    sa.ForeignKeyConstraint(['wave_id'], ['wave.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runhistory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runhistory_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runhistory_finished_at'), ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runhistory_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runhistory_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runhistory_wave_id'), ['wave_id'], unique=False)

    op.create_table('signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wave_id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=6), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ),
    sa.ForeignKeyConstraint(['wave_id'], ['wave.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.create_index('ix_signal_connector_created_at', ['connector_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_signal_dedupe_key', ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_type'), ['type'], unique=False)
        batch_op.create_index('ix_signal_wave_created_at', ['wave_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_wave_id'), ['wave_id'], unique=False)
        batch_op.create_index('ix_signal_wave_severity', ['wave_id', 'severity'], unique=False)
        batch_op.create_index('ix_signal_wave_status', ['wave_id', 'status'], unique=False)
        batch_op.create_index('ix_signal_wave_type', ['wave_id', 'type'], unique=False)

    op.create_table('sourcecheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discovered_source_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=7), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('parseable', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['discovered_source_id'], ['discoveredsource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sourcecheck', schema=None) as batch_op:
        batch_op.create_index('ix_source_check_source_checked_at', ['discovered_source_id', 'checked_at'], unique=False)
        batch_op.create_index('ix_source_check_source_reach_parse', ['discovered_source_id', 'reachable', 'parseable'], unique=False)
        batch_op.create_index('ix_source_check_source_status', ['discovered_source_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sourcecheck_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sourcecheck_discovered_source_id'), ['discovered_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sourcecheck_parseable'), ['parseable'], unique=False)
        batch_op.create_index(batch_op.f('ix_sourcecheck_reachable'), ['reachable'], unique=False)
        batch_op.create_index(batch_op.f('ix_sourcecheck_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sourcecheck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sourcecheck_status'))
        batch_op.drop_index(batch_op.f('ix_sourcecheck_reachable'))
        batch_op.drop_index(batch_op.f('ix_sourcecheck_parseable'))
        batch_op.drop_index(batch_op.f('ix_sourcecheck_discovered_source_id'))
        batch_op.drop_index(batch_op.f('ix_sourcecheck_checked_at'))
        batch_op.drop_index('ix_source_check_source_status')
        batch_op.drop_index('ix_source_check_source_reach_parse')
        batch_op.drop_index('ix_source_check_source_checked_at')

    op.drop_table('sourcecheck')
    with op.batch_alter_table('signal', schema=None) as batch_op:
        batch_op.drop_index('ix_signal_wave_type')
        batch_op.drop_index('ix_signal_wave_status')
        batch_op.drop_index('ix_signal_wave_severity')
        batch_op.drop_index(batch_op.f('ix_signal_wave_id'))
        batch_op.drop_index('ix_signal_wave_created_at')
        batch_op.drop_index(batch_op.f('ix_signal_type'))
        batch_op.drop_index(batch_op.f('ix_signal_status'))
        batch_op.drop_index(batch_op.f('ix_signal_severity'))
        batch_op.drop_index('ix_signal_dedupe_key')
        batch_op.drop_index(batch_op.f('ix_signal_created_at'))
        batch_op.drop_index(batch_op.f('ix_signal_connector_id'))
        batch_op.drop_index('ix_signal_connector_created_at')

    op.drop_table('signal')
    with op.batch_alter_table('runhistory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runhistory_wave_id'))
        batch_op.drop_index(batch_op.f('ix_runhistory_status'))
        batch_op.drop_index(batch_op.f('ix_runhistory_started_at'))
        batch_op.drop_index(batch_op.f('ix_runhistory_finished_at'))
        batch_op.drop_index(batch_op.f('ix_runhistory_connector_id'))

    op.drop_table('runhistory')
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_index('ux_record_connector_external_id')
        batch_op.drop_index('ix_record_wave_source_type_collected')
        batch_op.drop_index(batch_op.f('ix_record_wave_id'))
        batch_op.drop_index('ix_record_wave_collected_at')
        batch_op.drop_index(batch_op.f('ix_record_external_id'))
        batch_op.drop_index(batch_op.f('ix_record_event_time'))
        batch_op.drop_index(batch_op.f('ix_record_connector_id'))
        batch_op.drop_index('ix_record_connector_collected_at')
        batch_op.drop_index(batch_op.f('ix_record_collected_at'))

    op.drop_table('record')
    with op.batch_alter_table('discoveredsource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discoveredsource_wave_id'))
        batch_op.drop_index(batch_op.f('ix_discoveredsource_status'))
        batch_op.drop_index(batch_op.f('ix_discoveredsource_source_type'))
        batch_op.drop_index(batch_op.f('ix_discoveredsource_relevance_score'))
        batch_op.drop_index(batch_op.f('ix_discoveredsource_parent_domain'))
        batch_op.drop_index(batch_op.f('ix_discoveredsource_last_success_at'))
        batch_op.drop_index(batch_op.f('ix_discoveredsource_last_http_status'))
        batch_op.drop_index(batch_op.f('ix_discoveredsource_last_content_type'))
        batch_op.drop_index(batch_op.f('ix_discoveredsource_last_checked_at'))
        batch_op.drop_index(batch_op.f('ix_discoveredsource_free_access'))
        batch_op.drop_index(batch_op.f('ix_discoveredsource_failure_count'))
        batch_op.drop_index(batch_op.f('ix_discoveredsource_discovered_at'))
        batch_op.drop_index('ix_discovered_source_wave_url_unique')
        batch_op.drop_index('ix_discovered_source_wave_status')
        batch_op.drop_index('ix_discovered_source_wave_stability')
        batch_op.drop_index('ix_discovered_source_wave_source_type')
        batch_op.drop_index('ix_discovered_source_wave_relevance')
        batch_op.drop_index('ix_discovered_source_parent_domain')

    op.drop_table('discoveredsource')
    with op.batch_alter_table('connector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connector_wave_id'))
        batch_op.drop_index('ix_connector_wave_enabled')
        batch_op.drop_index(batch_op.f('ix_connector_type'))
        batch_op.drop_index(batch_op.f('ix_connector_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_connector_last_success_at'))
        batch_op.drop_index(batch_op.f('ix_connector_last_run_at'))
        batch_op.drop_index(batch_op.f('ix_connector_last_error_at'))
        batch_op.drop_index(batch_op.f('ix_connector_enabled'))

    op.drop_table('connector')
    with op.batch_alter_table('wave', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wave_status'))
        batch_op.drop_index(batch_op.f('ix_wave_name'))
        batch_op.drop_index(batch_op.f('ix_wave_last_success_at'))
        batch_op.drop_index(batch_op.f('ix_wave_last_run_at'))
        batch_op.drop_index(batch_op.f('ix_wave_last_error_at'))
        batch_op.drop_index(batch_op.f('ix_wave_focus_type'))

    op.drop_table('wave')
    # ### end Alembic commands ###
