import { buildAerospaceEvidenceTimelinePackageSummary } from "../src/features/inspector/aerospaceEvidenceTimelinePackage.ts";

function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

const summary = buildAerospaceEvidenceTimelinePackageSummary({
  selectedDataHealthSummary: {
    sourceKind: "observed-live",
    freshness: "recent",
    health: "normal",
    evidenceBasis: "observed",
    timestamp: "2026-05-04T20:00:00Z",
    timestampLabel: "Observed 2026-05-04T20:00:00Z",
    ageSeconds: 120,
    ageLabel: "2 min old",
    contextStatusLabel: "airport/runway context available",
    caveats: ["Selected-target timestamps remain bounded observed evidence."],
    displayLines: [],
  },
  weatherSummary: {
    airportCode: "KAUS",
    airportName: "Austin-Bergstrom International Airport",
    source: "noaa-awc",
    sourceDetail: "NOAA AWC",
    sourceHealthState: "healthy",
    metarAvailable: true,
    tafAvailable: true,
    metarReportedAt: "2026-05-04T19:55:00Z",
    tafIssuedAt: "2026-05-04T18:00:00Z",
    displayLines: [],
    caveats: ["Do not infer flight intent from METAR or TAF alone."],
  },
  airportStatusSummary: {
    airportCode: "KAUS",
    airportName: "Austin-Bergstrom International Airport",
    statusType: "advisory",
    summary: "Advisory in effect",
    sourceMode: "fixture",
    sourceHealth: "normal",
    updatedAt: "2026-05-04T19:40:00Z",
    displayLines: [],
    caveats: ["FAA NAS airport status is contextual/advisory airport information and is not flight-specific."],
  },
  referenceSummary: {
    source: "ourairports-reference",
    sourceMode: "fixture",
    sourceHealth: "normal",
    sourceState: "healthy",
    airportCount: 1,
    runwayCount: 2,
    selectedAirportCode: "KAUS",
    selectedAirportName: "Austin-Bergstrom International Airport",
    selectedRegionCode: "US-TX",
    selectedRunwayCode: "17L",
    airportMatchStatus: "exact-airport-code",
    runwayMatchStatus: "runway-ident-match",
    matchedAirport: null,
    matchedRunway: null,
    comparisonLine: "Reference comparison: exact airport code matched baseline facility metadata",
    displayLines: [],
    exportLines: [],
    caveats: ["OurAirports reference context is baseline facility metadata only and does not replace live selected-target evidence."],
    doesNotProve: [],
  },
  openSkySummary: {
    source: "opensky-anonymous-states",
    sourceMode: "fixture",
    sourceHealth: "normal",
    sourceState: "healthy",
    aircraftCount: 1,
    matchedState: {
      icao24: "abc123",
      callsign: "DAL123",
      originCountry: "United States",
      timePosition: "2026-05-04T19:58:00Z",
      lastContact: "2026-05-04T19:59:00Z",
      longitude: -97.66,
      latitude: 30.19,
      baroAltitude: 1000,
      onGround: false,
      velocity: 210,
      trueTrack: 180,
      verticalRate: 0,
      geoAltitude: 1020,
      squawk: null,
      spi: false,
      positionSource: "adsb_icao",
      sourceMode: "fixture",
      caveats: [],
      evidenceBasis: "observed",
    },
    selectedTargetComparison: {
      matchStatus: "exact-icao",
      selectedTargetId: "aircraft:test-abc123",
      selectedCallsign: "DAL123",
      selectedIcao24: "abc123",
      matchedOpenSkyIcao24: "abc123",
      matchedOpenSkyCallsign: "DAL123",
      timeDifferenceSeconds: 30,
      positionDifferenceKm: 0.8,
      caveats: ["OpenSky anonymous state vectors are optional, rate-limited, and source-reported only."],
      evidenceBasis: "source-reported",
    },
    displayLines: [],
    caveats: ["Coverage is not guaranteed to be complete or authoritative."],
  },
  swpcSummary: {
    source: "noaa-swpc",
    sourceMode: "fixture",
    sourceHealth: "normal",
    sourceState: "healthy",
    summaryCount: 1,
    alertCount: 1,
    topSummary: {
      productId: "sum-1",
      productType: "scale-summary",
      issuedAt: "2026-05-04T17:00:00Z",
      observedAt: null,
      updatedAt: "2026-05-04T17:10:00Z",
      scaleCategory: "G1",
      headline: "Minor geomagnetic activity",
      description: "Minor activity.",
      affectedContext: ["geomagnetic"],
      sourceUrl: null,
      sourceMode: "fixture",
      health: "normal",
      caveats: [],
      evidenceBasis: "advisory",
    },
    topAlert: {
      productId: "alert-1",
      productType: "advisory",
      issuedAt: "2026-05-04T18:30:00Z",
      updatedAt: null,
      scaleCategory: "R1",
      headline: "Minor radio advisory",
      description: "Minor radio advisory.",
      affectedContext: ["radio"],
      sourceUrl: null,
      sourceMode: "fixture",
      health: "normal",
      caveats: [],
      evidenceBasis: "advisory",
    },
    affectedContext: ["radio", "geomagnetic"],
    displayLines: [],
    caveats: ["Do not infer satellite, GPS, or radio failure unless the source explicitly states that impact."],
  },
  nceiArchiveSummary: {
    source: "noaa-ncei-space-weather-portal",
    sourceMode: "fixture",
    sourceHealth: "normal",
    sourceState: "healthy",
    recordCount: 1,
    record: null,
    collectionId: "gov.noaa.ngdc.stp.swx:space_weather_products",
    datasetIdentifier: "space_weather_products",
    title: "Space Weather Products",
    temporalStart: "1932-01-01",
    temporalEnd: "2026-05-01",
    metadataUpdatedAt: "2026-05-01T00:00:00Z",
    progressStatus: "completed",
    updateFrequency: "daily",
    metadataSourceUrl: "https://example.test/xml",
    landingPageUrl: "https://example.test/page",
    displayLines: [],
    caveats: ["NOAA NCEI archive metadata is archival/contextual and remains separate from current NOAA SWPC advisories."],
  },
  vaacSummary: {
    sourceCount: 1,
    healthySourceCount: 1,
    availableSourceCount: 1,
    totalAdvisoryCount: 1,
    sourceModes: ["fixture"],
    sources: [
      {
        sourceId: "washington-vaac",
        label: "Washington VAAC",
        source: "washington-vaac",
        sourceMode: "fixture",
        sourceHealth: "normal",
        sourceState: "healthy",
        listingSourceUrl: "https://example.test/vaac",
        advisoryCount: 1,
        available: true,
        topAdvisory: {
          advisoryId: "vaa-1",
          advisoryNumber: "001",
          issueTime: "2026-05-04T16:00:00Z",
          observedAt: null,
          volcanoName: "Fuego",
          volcanoNumber: null,
          areaOrRegion: null,
          maxFlightLevel: "200",
          aviationColorCode: null,
          sourceUrl: null,
          evidenceBasis: "advisory",
          summaryText: "Source-reported advisory context",
        },
        caveats: ["VAAC advisories are contextual volcanic-ash source reports and do not by themselves prove route impact or aircraft exposure."],
      },
    ],
    displayLines: [],
    exportLines: [],
    caveats: ["Do not infer engine risk, operational consequence, or action recommendation from this summary alone."],
    doesNotProve: [],
    metadata: {
      sourceCount: 1,
      healthySourceCount: 1,
      availableSourceCount: 1,
      totalAdvisoryCount: 1,
      sourceModes: ["fixture"],
      sources: [],
      caveats: [],
      doesNotProve: [],
    },
  },
  availabilitySummary: {
    rows: [],
    availableCount: 4,
    unavailableCount: 1,
    degradedCount: 1,
    fixtureSourceCount: 5,
    caveats: ["Availability means present or absent context only."],
    exportLines: [],
    compactLine: "Availability accounting",
  },
  workflowValidationSnapshotSummary: {
    snapshotId: "aerospace-workflow-validation-evidence",
    snapshotLabel: "Aerospace Workflow Validation Evidence",
    posture: "blocked-smoke-environment",
    preparedSmokeStatus: "prepared",
    executedSmokeStatus: "blocked",
    selectedTargetReportReady: true,
    missingEvidenceCount: 2,
    sourceIds: ["noaa-awc", "noaa-swpc"],
    sourceModes: ["fixture"],
    sourceHealthStates: ["healthy"],
    evidenceBases: ["observed", "advisory"],
    guardrailLine: "Workflow-validation evidence snapshots are validation-accounting only.",
    displayLines: [],
    exportLines: [],
    caveats: ["Prepared smoke remains prepared smoke."],
    metadata: {
      snapshotId: "aerospace-workflow-validation-evidence",
      snapshotLabel: "Aerospace Workflow Validation Evidence",
      posture: "blocked-smoke-environment",
      preparedSmokeStatus: "prepared",
      executedSmokeStatus: "blocked",
      selectedTargetReportReady: true,
      missingEvidenceCount: 2,
      sourceIds: ["noaa-awc", "noaa-swpc"],
      sourceModes: ["fixture"],
      sourceHealthStates: ["healthy"],
      evidenceBases: ["observed", "advisory"],
      guardrailLine: "Workflow-validation evidence snapshots are validation-accounting only.",
      reportProfileId: "default",
      reportProfileLabel: "Default Snapshot Report",
      reviewQueueItemCount: 1,
      reviewExportBundleItemCount: 1,
      workflowValidationRows: 2,
      caveats: ["Prepared smoke remains prepared smoke."],
    },
  },
  workflowReadinessPackageSummary: {
    packageId: "aerospace-workflow-readiness",
    packageLabel: "Aerospace Workflow Readiness",
    sourceIds: ["workflow-smoke"],
    sourceModes: ["fixture"],
    sourceHealthStates: ["healthy"],
    evidenceBases: ["validation"],
    preparedSmokeStatus: "prepared",
    executedSmokeStatus: "blocked",
    validationRows: [],
    missingEvidenceRows: [
      {
        kind: "validation",
        sourceId: "workflow-smoke",
        label: "Executed aerospace smoke status",
        status: "blocked",
        reason: "browser workflow evidence is blocked before app assertions",
        caveat: "Playwright Chromium launch failed before app assertions.",
      },
    ],
    guardrailLine: "Workflow readiness packages are evidence-accounting only.",
    displayLines: [],
    exportLines: [],
    caveats: ["Prepared smoke assertions are not executed smoke evidence."],
    metadata: {
      packageId: "aerospace-workflow-readiness",
      packageLabel: "Aerospace Workflow Readiness",
      sourceIds: ["workflow-smoke"],
      sourceModes: ["fixture"],
      sourceHealthStates: ["healthy"],
      evidenceBases: ["validation"],
      preparedSmokeStatus: "prepared",
      executedSmokeStatus: "blocked",
      validationRows: [],
      missingEvidenceRows: [
        {
          kind: "validation",
          sourceId: "workflow-smoke",
          label: "Executed aerospace smoke status",
          status: "blocked",
          reason: "browser workflow evidence is blocked before app assertions",
          caveat: "Playwright Chromium launch failed before app assertions.",
        },
      ],
      exportProfileId: "compact-evidence",
      exportProfileLabel: "Compact Evidence",
      guardrailLine: "Workflow readiness packages are evidence-accounting only.",
      caveats: ["Prepared smoke assertions are not executed smoke evidence."],
    },
  },
});

assert(summary, "Expected aerospace evidence timeline summary.");
assert(summary.packageId === "aerospace-evidence-timeline", "Expected evidence timeline package id.");
assert(summary.entryClasses.includes("observed"), "Expected observed entry class.");
assert(summary.entryClasses.includes("forecast"), "Expected forecast entry class.");
assert(summary.entryClasses.includes("archive"), "Expected archive entry class.");
assert(summary.entryClasses.includes("reference"), "Expected reference entry class.");
assert(summary.entryClasses.includes("anonymous-comparison"), "Expected anonymous-comparison entry class.");
assert(summary.entryClasses.includes("validation"), "Expected validation entry class.");
assert(
  summary.exportLines.some((line) => line.includes("prepared=prepared") && line.includes("executed=blocked")),
  "Expected smoke posture line in export output."
);
assert(
  summary.metadata.missingEvidenceRows.some((row) => row.sourceId === "workflow-smoke"),
  "Expected workflow-smoke missing evidence row."
);
assert(
  summary.guardrailLine.includes("timeline order is not causation"),
  "Expected timeline guardrail to preserve non-causation wording."
);
assert(
  summary.entries.some((entry) => entry.entryClass === "forecast" && entry.label.includes("TAF")),
  "Expected forecast TAF entry."
);
assert(
  summary.entries.some((entry) => entry.entryClass === "archive" && entry.sourceId === "noaa-ncei-space-weather-portal"),
  "Expected archive entry."
);

console.log(
  JSON.stringify(
    {
      packageId: summary.packageId,
      entryCount: summary.entryCount,
      entryClasses: summary.entryClasses,
      topEntry: summary.metadata.topEntry?.entryId ?? null,
      missingEvidenceRows: summary.metadata.missingEvidenceRows.length,
    },
    null,
    2
  )
);
