import { buildAerospaceFusionSnapshotInputSummary } from "../src/features/inspector/aerospaceFusionSnapshotInput.ts";

const summary = buildAerospaceFusionSnapshotInputSummary({
  selectedTargetSummary: {
    type: "aircraft",
    entityId: "aircraft:test",
    label: "TEST123",
    callsign: "TEST123",
    sourceLabel: "Observed session history",
    latestObservationAge: "1 minute",
    sessionPointCount: 6,
    firstObservedAt: "2026-05-04T21:30:00Z",
    latestObservedAt: "2026-05-04T21:35:00Z",
    sessionDistanceKm: 12.4,
    altitudeTrend: "steady",
    speedTrend: "steady",
    headingBehavior: "stable",
    nearestAirportContext: "near airport context",
    nearestRunwayContext: "runway threshold context unavailable",
    caveat: "Observed aircraft history is session-only and does not prove intent.",
    displayLines: ["Movement source: observed session", "Session points: 6"],
  },
  contextSnapshotReportSummary: {
    profileId: "default",
    profileLabel: "Default Snapshot Report",
    issueCount: 2,
    reviewLineCount: 2,
    sourceIds: ["awc", "swpc"],
    sourceModes: ["fixture"],
    sourceHealthStates: ["healthy"],
    evidenceBases: ["observed", "advisory"],
    missingMetadataKeys: [],
    missingFooterSections: [],
    guardrailLine: "Snapshot/report packages do not imply severity.",
    reviewLines: ["Top report line"],
    exportLines: ["Snapshot/report package: Default Snapshot Report"],
    caveats: ["Snapshot/report packages do not imply severity."],
    bannedOperationalPhrasesPresent: [],
    metadata: {},
  },
  contextReviewQueueSummary: {
    queueId: "aerospace-context-review-queue",
    queueLabel: "Aerospace Context Review Queue",
    itemCount: 3,
    reviewFirstCount: 1,
    reviewCount: 1,
    noteCount: 1,
    activeContextProfileId: "compact-evidence",
    activeContextProfileLabel: "Compact Evidence",
    sourceIds: ["opensky-anonymous-states", "faa-nas-status"],
    sourceModes: ["fixture"],
    sourceHealthStates: ["healthy"],
    evidenceBases: ["contextual", "advisory"],
    topItems: [
      {
        itemId: "workflow-smoke-prepared",
        kind: "prepared-smoke-without-executed",
        priority: "review-first",
        label: "Executed Aerospace Smoke",
        sourceIds: ["workflow-smoke"],
        sourceModes: [],
        sourceHealthStates: ["prepared"],
        evidenceBases: ["contextual"],
        reviewLine: "Prepared assertions exist.",
        exportSafeLine: "Prepared assertions exist.",
        caveat: "Prepared smoke is not executed smoke.",
        guardrailLine: "Queue items are review/accounting summaries only.",
      },
    ],
    guardrailLine: "Queue items are review/accounting summaries only.",
    displayLines: [],
    exportLines: ["Context review queue: 3 items"],
    caveats: ["Prepared smoke is not executed smoke."],
    metadata: {
      items: [
        {
          itemId: "workflow-smoke-prepared",
          kind: "prepared-smoke-without-executed",
          priority: "review-first",
          label: "Executed Aerospace Smoke",
          sourceIds: ["workflow-smoke"],
          sourceModes: [],
          sourceHealthStates: ["prepared"],
          evidenceBases: ["contextual"],
          reviewLine: "Prepared assertions exist.",
          exportSafeLine: "Prepared assertions exist.",
          caveat: "Prepared smoke is not executed smoke.",
          guardrailLine: "Queue items are review/accounting summaries only.",
        },
      ],
      caveats: ["Prepared smoke is not executed smoke."],
    },
  },
  contextReviewExportBundleSummary: {
    bundleId: "aerospace-context-review-export-bundle",
    bundleLabel: "Aerospace Context Review Export Bundle",
    itemCount: 3,
    activeContextProfileId: "compact-evidence",
    activeContextProfileLabel: "Compact Evidence",
    sourceIds: ["workflow-smoke"],
    sourceModes: ["fixture"],
    sourceHealthStates: ["prepared"],
    evidenceBases: ["contextual"],
    guardrailLine: "Review-safe lines and caveats only.",
    reviewLines: ["Prepared assertions exist."],
    exportLines: ["Context review export bundle: 3 items"],
    caveats: ["Prepared smoke is not executed smoke."],
    metadata: { items: [] },
  },
  issueExportBundleSummary: {
    issueCount: 2,
    reviewOnlyCount: 2,
    sourceIds: ["swpc", "ncei"],
    sourceModes: ["fixture"],
    sourceHealthStates: ["healthy"],
    evidenceBases: ["advisory", "archive"],
    guardrailLine: "Issue export bundles do not imply severity.",
    topItems: [
      {
        itemId: "current-archive-separation",
        category: "current-archive-separation",
        title: "Current vs Archive",
        summary: "Current/archive separation: separated",
        exportLine: "Current/archive separation maintained",
        sourceIds: ["swpc", "ncei"],
        sourceModes: ["fixture"],
        sourceHealthStates: ["healthy"],
        evidenceBases: ["advisory", "archive"],
        caveats: ["Archive is not current warning truth."],
        guardrailLines: ["Issue export bundles do not imply severity."],
        missingMetadataKeys: [],
        missingFooterSections: [],
      },
    ],
    displayLines: [],
    exportLines: ["Issue export bundle: 2 review items"],
    caveats: ["Archive is not current warning truth."],
    bannedOperationalPhrasesPresent: [],
    metadata: { items: [] },
  },
  workflowReadinessPackageSummary: {
    packageId: "aerospace-workflow-readiness",
    packageLabel: "Aerospace Workflow Readiness",
    sourceIds: ["ourairports-reference"],
    sourceModes: ["fixture"],
    sourceHealthStates: ["healthy"],
    evidenceBases: ["reference"],
    preparedSmokeStatus: "prepared",
    executedSmokeStatus: "blocked",
    validationRows: [],
    missingEvidenceRows: [{ kind: "validation", sourceId: "workflow-smoke", label: "Smoke", status: "blocked", reason: "spawn EPERM", caveat: "Blocked before app assertions." }],
    guardrailLine: "Workflow readiness is evidence-accounting only.",
    displayLines: [],
    exportLines: ["Workflow readiness: prepared smoke only"],
    caveats: ["Blocked before app assertions."],
    metadata: {},
  },
  workflowValidationEvidenceSnapshotSummary: {
    snapshotId: "aerospace-workflow-validation-evidence",
    snapshotLabel: "Aerospace Workflow Validation Evidence",
    posture: "blocked-smoke-environment",
    preparedSmokeStatus: "prepared",
    executedSmokeStatus: "blocked",
    selectedTargetReportReady: true,
    missingEvidenceCount: 1,
    sourceIds: ["workflow-smoke"],
    sourceModes: ["fixture"],
    sourceHealthStates: ["blocked"],
    evidenceBases: ["validation"],
    guardrailLine: "Validation-accounting only.",
    displayLines: ["Validation posture: blocked by smoke environment"],
    exportLines: ["Workflow validation: blocked by smoke environment"],
    caveats: ["Blocked before app assertions."],
    metadata: {},
  },
  evidenceTimelinePackageSummary: {
    packageId: "aerospace-evidence-timeline",
    packageLabel: "Aerospace Evidence Timeline",
    entryCount: 4,
    entryClasses: ["observed", "forecast", "archive", "anonymous-comparison", "validation"],
    sourceIds: ["awc", "ncei", "opensky-anonymous-states"],
    sourceModes: ["fixture"],
    sourceHealthStates: ["healthy"],
    evidenceBases: ["observed", "forecast", "archive", "source-reported", "validation"],
    preparedSmokeStatus: "prepared",
    executedSmokeStatus: "blocked",
    selectedTargetTimestamp: "2026-05-04T21:35:00Z",
    missingEvidenceRows: [{ kind: "validation", sourceId: "workflow-smoke", label: "Smoke", status: "blocked", reason: "spawn EPERM", caveat: "Blocked before app assertions." }],
    guardrailLine: "Timeline order is not causation.",
    displayLines: [],
    exportLines: ["Evidence timeline: 4 entries"],
    caveats: ["Timeline order is not causation."],
    entries: [
      { entryId: "awc-metar", label: "Aviation weather METAR", entryClass: "observed", sourceId: "awc", sourceMode: "fixture", sourceHealthState: "healthy", evidenceBasis: "observed", timestamp: "2026-05-04T21:34:00Z", timestampLabel: "METAR report", summary: "Airport observation", caveat: "Observed only." },
      { entryId: "awc-taf", label: "Aviation weather TAF", entryClass: "forecast", sourceId: "awc", sourceMode: "fixture", sourceHealthState: "healthy", evidenceBasis: "forecast", timestamp: "2026-05-04T21:20:00Z", timestampLabel: "TAF issue", summary: "Forecast context", caveat: "Forecast only." },
      { entryId: "ncei", label: "NCEI archive", entryClass: "archive", sourceId: "ncei", sourceMode: "fixture", sourceHealthState: "healthy", evidenceBasis: "archive", timestamp: "2026-05-04T20:00:00Z", timestampLabel: "Archive metadata updated", summary: "Archive metadata", caveat: "Archive only." },
      { entryId: "opensky", label: "OpenSky anonymous comparison", entryClass: "anonymous-comparison", sourceId: "opensky-anonymous-states", sourceMode: "fixture", sourceHealthState: "healthy", evidenceBasis: "source-reported", timestamp: "2026-05-04T21:33:00Z", timestampLabel: "OpenSky time-position", summary: "Comparison match status no-match", caveat: "No match does not prove absence." },
      { entryId: "validation", label: "Workflow validation posture", entryClass: "validation", sourceId: "workflow-smoke", sourceMode: null, sourceHealthState: "blocked", evidenceBasis: "validation", timestamp: null, timestampLabel: "Validation posture", summary: "prepared=prepared | executed=blocked", caveat: "Blocked before app assertions." },
    ],
    metadata: {},
  },
  packageCoherenceSummary: {
    packageId: "aerospace-package-coherence",
    packageLabel: "Aerospace Package Coherence",
    coherenceState: "aligned",
    packageCount: 7,
    findingCount: 9,
    reviewFindingCount: 0,
    sourceIds: ["awc", "ncei", "workflow-smoke"],
    sourceModes: ["fixture"],
    sourceHealthStates: ["healthy", "blocked"],
    evidenceBases: ["observed", "archive", "validation"],
    alignedMetadataKeys: ["aerospaceContextReviewQueue"],
    missingMetadataKeys: [],
    guardrailLine: "Package coherence is metadata/accounting only.",
    findings: [],
    displayLines: ["Package coherence: aligned"],
    exportLines: ["Package coherence: aligned"],
    caveats: ["Package coherence is metadata/accounting only."],
    metadata: {},
  },
  exportProfileSummary: {
    profileId: "compact-evidence",
    profileLabel: "Compact Evidence",
    includedSections: ["selected-target", "fusion-snapshot-input"],
    caveat: "Compact evidence keeps footer output short.",
    footerLines: [],
    metadata: {
      profileId: "compact-evidence",
      profileLabel: "Compact Evidence",
      includedSections: ["selected-target", "fusion-snapshot-input"],
      includedMetadataKeys: ["aerospaceFusionSnapshotInput"],
      caveat: "Compact evidence keeps footer output short.",
    },
  },
  exportReadinessSummary: {
    category: "ready-with-caveats",
    label: "ready with caveats",
    reviewRecommended: false,
    sourceCount: 5,
    healthySourceCount: 4,
    availableCount: 4,
    unavailableCount: 0,
    degradedCount: 0,
    fixtureSourceCount: 4,
    issueCount: 2,
    attentionCount: 1,
    topReason: "Core export context is present.",
    displayLines: [],
    exportLines: ["Export readiness: ready with caveats"],
    caveats: ["Export readiness summarizes context completeness only."],
    metadata: { topSourceIds: ["awc"], caveats: ["Export readiness summarizes context completeness only."] },
  },
});

if (!summary) {
  throw new Error("Expected aerospace fusion snapshot input summary.");
}
if (summary.packageId !== "aerospace-fusion-snapshot-input") {
  throw new Error(`Unexpected fusion package id: ${summary.packageId}`);
}
if (summary.activeContextProfileLabel !== "Compact Evidence") {
  throw new Error(`Unexpected fusion profile label: ${summary.activeContextProfileLabel}`);
}
if (summary.validationPosture !== "blocked-smoke-environment") {
  throw new Error(`Unexpected fusion validation posture: ${summary.validationPosture}`);
}
if (summary.exportReadinessCategory !== "ready-with-caveats") {
  throw new Error(`Unexpected fusion readiness category: ${summary.exportReadinessCategory}`);
}
if (!summary.sections.some((section) => section.sectionId === "archive")) {
  throw new Error("Fusion summary missing archive section.");
}
if (!summary.sections.some((section) => section.sectionId === "anonymous-comparison")) {
  throw new Error("Fusion summary missing anonymous-comparison section.");
}
if (!summary.doesNotProveLines.some((line) => line.includes("does not prove flight intent"))) {
  throw new Error("Fusion summary missing does-not-prove guardrail.");
}

console.log(
  JSON.stringify(
    {
      packageId: summary.packageId,
      sections: summary.sections.map((section) => section.sectionId),
      validationPosture: summary.validationPosture,
      exportReadinessCategory: summary.exportReadinessCategory,
      sourceCount: summary.sourceIds.length,
    },
    null,
    2
  )
);
